name: "rnnt_greedy"
backend: "python"
max_batch_size: 32

input [
  { name: "AUDIO_SIGNAL", data_type: TYPE_FP32, dims: [ -1 ] },   # 1-D PCM float32
  { name: "AUDIO_LENGTH", data_type: TYPE_INT32, dims: [ 1 ] }
]

output [
  { name: "TRANSCRIPT", data_type: TYPE_STRING, dims: [ -1 ] }
]

parameters: {
  key: "nemo_model_path"
  value: { string_value: "rnnt_asr.nemo" }
}
parameters: {
  key: "encoder_path"
  value: { string_value: "encoder-vpb_fastconformer.onnx" }
}
parameters: {
  key: "decoder_path"
  value: { string_value: "decoder_joint-vpb_fastconformer.onnx" }
}

dynamic_batching {
  preferred_batch_size: [ 4, 8, 16, 32 ]
  max_queue_delay_microseconds: 15000
}

instance_group [
  { kind: KIND_CPU, count: 2 }   # đổi sang KIND_GPU nếu muốn chạy GPU
]
